# Generated by Django 5.0.6 on 2024-06-15 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0004_customer_delete_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
